[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://snapgram-social-media-app.netlify.app"
    Access-Control-Allow-Credentials = "true"
